server:
  port: 80 
  servlet:
    context-path: / 
  tomcat: 
    max-threads: 1000
    
    
spring: 
  datasource: 
    url: jdbc:mysql:///sportdb?serverTimezone=GMT%2B8&characterEncoding=UTF8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/pages/


mybatis-plus:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/*/*.xml

